//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public Nullable<int> idT { get; set; }
        public Nullable<int> idAutora { get; set; }
        public Nullable<System.DateTime> czas { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> czas_edycji { get; set; }
        public string tresc { get; set; }
    
        public virtual Temat Temat { get; set; }
        public virtual User User { get; set; }
    }
}
